version: "2"
services:
  mysql56:
    ports:
      - "10056:3306"
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  mysql57:
    ports:
      - "10057:3306"
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
